language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install six
  - pip install -r code_court/courthouse/requirements.txt
  - pip install -r code_court/executor/requirements.txt
script:
  - cd code_court/courthouse/
  - nosetests
  - cd ../executor
  - nosetests
