language: python
python:
  - "3.8"
install:
  - pip install six
  - pip install -r code_court/courthouse/requirements.txt
  - pip install -r code_court/executor/requirements.txt
  - pip install black
script:
  - cd code_court/courthouse/
  - nosetests
  - black --check
  - cd ../executor
  - nosetests
